services:
  db:
    image: postgis/postgis:18-3.6
    environment:
      - POSTGRES_DB=gasjadb
      - POSTGRES_PASSWORD=gasjaapp
      - POSTGRES_USER=postgres
    ports:
      - '5532:5432'

  adminer:
    image: adminer
    ports:
      - '9090:8080'
    depends_on:
      - db