spring:
  application:
    name: gasja-api

    datasource:
      url: jdbc:postgresql://localhost:5432/gasjadb
      username: postgres
      password: gasjaapp

    jpa:
      show-sql: true
      format-sql: true
